# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.4.1
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: petar@elab.rs
author_name: Petar
cloud_provider: none
contract_name: hello_world
ide_vscode: true
preset_name: starter
project_name: fullstack-demo
python_linter: none
use_dispenser: false
use_github_actions: true
use_python_black: true
use_python_mypy: false
use_python_pip_audit: true
use_python_pytest: false

